spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
  flyway:
    enabled: true
app:
  mail:
    provider: resend
